version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    environment:
      - DB_HOST=db
      - DB_NAME=theeye-dev
      - DB_USER=theeyeadmin
      - DB_PASS=NZaDCa6GyDvr3Rdv
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=theeye-dev
      - POSTGRES_USER=theeyeadmin
      - POSTGRES_PASSWORD=NZaDCa6GyDvr3Rdv
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
    command: celery worker --app=app --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=theeye-dev
      - DB_USER=theeyeadmin
      - DB_PASS=NZaDCa6GyDvr3Rdv
    depends_on:
      - db
      - app
      - redis

  redis:
    image: redis:6-alpine
