# Generated by Django 4.0.2 on 2022-02-17 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the app', max_length=30)),
                ('user', models.ForeignKey(help_text='User that owns the app', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Event category slug to identify the category', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public session identifier', unique=True)),
                ('timestamp', models.DateField(auto_now_add=True, help_text='Session creation timestamp')),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata for the session', null=True)),
                ('application', models.ForeignKey(help_text='Application that creates the session', on_delete=django.db.models.deletion.CASCADE, to='events.application')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name', max_length=100)),
                ('data', models.JSONField(help_text='Data required for the event')),
                ('timestamp', models.DateField(auto_now_add=True, help_text='Event creation timestamp')),
                ('category', models.ForeignKey(help_text='Category related to event', on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory')),
                ('session', models.ForeignKey(help_text='Session related to event', on_delete=django.db.models.deletion.CASCADE, to='events.session')),
            ],
        ),
    ]
